### ISSUE TITLE
File Manager: Issues with downloading files

### ISSUE THREAD

**Issue by sohamb03** [madeITBelgium/vesta#101]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

0.0.25

---

While trying to download any file from the File Manager, the size of the downloaded file is always 0 KB. This is regardless of the file extension, the issue can be reproduced with any random file, whether you click on it to download, or select it and press the "Download" button.

**Comment by madeITBelgium** [comment]
I can't reproduce this on a newly installed server.
