### ISSUE TITLE
Rocky Linux 8.4 is here

### ISSUE THREAD

**Issue by Neustradamus** [madeITBelgium/vesta#106]
Rocky Linux 8.4 is here:
- https://rockylinux.org/news/rocky-linux-8-4-ga-release/

It is linked to:
- https://github.com/serghey-rodin/vesta/issues/1956
- https://github.com/serghey-rodin/vesta/issues/2000
- https://github.com/serghey-rodin/vesta/issues/2056

**Comment by madeITBelgium** [comment]
This repo works on Alma Linux, So I guess also on Rocky Linux.
