### ISSUE TITLE
Alma Linux 9.1 & Rocky Linux 91

### ISSUE THREAD

**Issue by RevengeFNF** [madeITBelgium/vesta#122]
Are you thinking in giving your script support to the new 9.x versions in the future?

Regards

**Comment by tummybos** [comment]
I am also curious about this. Whats the use of a system with so much rich features but no support for latest OS?

**Comment by madeITBelgium** [comment]
At this point I haven't needed almalinux 9 yet. So there has been no need for me to provide support yet. You are free to send a pull request and I will be happy to add support. If I need Alma Linux or Centos 9 myself, I will make the necessary changes myself.

**Comment by madeITBelgium** [comment]
We have added support for almalinux 9 in Beta:

Install:
curl -o https://raw.githubusercontent.com/madeITBelgium/vesta/master/install/vst-install-rhel.sh
