### ISSUE TITLE
Invalid Login after restore VestaCP Backup

### ISSUE THREAD

**Issue by RevengeFNF** [madeITBelgium/vesta#123]
### Operating System (OS/VERSION):

Almalinux 8

### VestaCP Version:

Last version

### Installed Software (what you got with the installer):

Type here, e.g. php-fpm, nginx, mysql, exim

### Steps to Reproduce:

I installed vesta, and everything worked and i was able to do the login.

I restored a VestaCP backup from Centos 7, and after the backup was completed, i wasn't able to login anymore.

I used this command to change the password: /usr/local/vesta/bin/v-change-user-password
Login still does not work.

I check the logs, and i got this error:

`2023/03/01 03:03:20 [error] 2177#0: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/vesta/web/inc/plugin.php on line 127 PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/vesta/web/login/index.php on line 137" while reading response header from upstream`

**Comment by madeITBelgium** [comment]
Hi, I just committed a fix for the error. I guess it has nothing to do with the problem you have.

SSH/FTP is still working on that account?

**Comment by RevengeFNF** [comment]
> Hi, I just committed a fix for the error. I guess it has nothing to do with the problem you have.
> 
> SSH/FTP is still working on that account?

Yes, i still have ssh/ftp working on the account. I will manualy apply your plugin.php fix and check if it works.

I will get back to you with feedback.

**Comment by RevengeFNF** [comment]
@madeITBelgium i updated the plugin.php, and that part disappeared from the error log, now it only shows this:

`2023/03/01 14:55:38 [error] 2177#0: *116 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/vesta/web/login/index.php on line 137" while reading response header from upstream`

Foreach() error in index.php inside login folder. Probably same thing?

**Comment by madeITBelgium** [comment]
Can you try this command and show me the output? 

`v-list-sys-config json`

If needed you may sent it to info@madeit.be

**Comment by RevengeFNF** [comment]
@madeITBelgium no issues to post it here.

` "config": {
        "WEB_SYSTEM": "nginx",
        "WEB_RGROUPS": "",
        "WEB_PORT": "80",
        "WEB_SSL": "openssl",
        "WEB_SSL_PORT": "443",
        "WEB_BACKEND": "php-fpm",
        "PROXY_SYSTEM": "",
        "PROXY_PORT": "",
        "PROXY_SSL_PORT": "",
        "FTP_SYSTEM": "proftpd",
        "MAIL_SYSTEM": "exim",
        "IMAP_SYSTEM": "dovecot",
        "ANTIVIRUS_SYSTEM": "",
        "ANTISPAM_SYSTEM": "spamassassin",
        "DB_SYSTEM": "mysql",
        "DNS_SYSTEM": "named",
        "DNS_CLUSTER": "",
        "STATS_SYSTEM": "awstats",
        "BACKUP_SYSTEM": "local",
        "CRON_SYSTEM": "crond",
        "DISK_QUOTA": "",
        "FIREWALL_SYSTEM": "iptables",
        "FIREWALL_EXTENSION": "fail2ban",
        "FILEMANAGER_KEY": "",
        "SFTPJAIL_KEY": "",
        "REPOSITORY": "",
        "VERSION": "0.0.35",
        "LANGUAGE": "en",
        "BACKUP_GZIP": "",
        "BACKUP": "",
        "MAIL_URL": "",
        "DB_PMA_URL": "",
        "DB_PGA_URL": "",
        "SOFTACULOUS": "",
        "LETSENCRYPT": "no"
    }
`

**Comment by RevengeFNF** [comment]
@madeITBelgium just a note, i don't need to try to login to get the error in index.pt, i just need to enter the /login page, and it will show that error on the logs.
