### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by robindirksen1** [madeITBelgium/vesta#5]
Any news about the automated docker build?

**Comment by madeITBelgium** [comment]
The docker build isn't stable at this moment. It is not really on my priority list right know. It was meant for testing permose (unit/automation testing).

**Comment by robindirksen1** [comment]
Ow okay, I will try to figure this out and let you know how it works! This way we can build the correct files for the c.vestacp.com site which can be automatically so the testing of the CP can be easier.

**Comment by madeITBelgium** [comment]
Oke thanks!
Here it was working: https://travis-ci.org/madeITBelgium/vesta/jobs/295008004
https://github.com/madeITBelgium/vesta/tree/0.0.4

**Comment by madeITBelgium** [comment]
I didn't fix the docker issue. But I created a test suite that starts a digital ocean container, installs this vesta repo and execute basic tests. Not all test are working but I will fix that later in #14
