### ISSUE TITLE
Editing web domain settings adds multiple blank DNS entries

### ISSUE THREAD

**Issue by kristankenney** [madeITBelgium/vesta#57]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

0.0.16

### Installed Software (what you got with the installer):

Default installation - apache, nginx, php, exim, dovecot, clamav, spamassassin

### Steps to Reproduce:

When changing a web domains settings (such as adding additional FTP accounts or aliases), duplicate DNS entries are created in the domain's zone file for both IPv4 and IPv6 (even if there is no IPv6 address) with blank values, causing the named service to fail on restart.

Rebuilding user/web/DNS also has no effect.

### Related Issues/Forum Threads:

Possibly related to #38 or #24?

### Screenshot:

![screen shot 2019-02-19 at 1 58 04 am](https://user-images.githubusercontent.com/40798553/52993250-f017d100-33e9-11e9-93b0-a31f320030ad.png)

**Comment by madeITBelgium** [comment]
Thank you for your bug report. I will check this. Currently, I cannot reproduce this but I will take a closer look at it. Is it may be possible to send me an e-mail at info@madeit.be , to discuss some debugging on your server?
