### ISSUE TITLE
debian support?

### ISSUE THREAD

**Issue by PHPScaresMe** [madeITBelgium/vesta#71]
### Operating System (OS/VERSION):

Debian 9.3

### VestaCP Version:

0.9.8 26

I installed vesta as per readme instructions in your repo but the ipv6 stuff is missing. Does that mean it's only for RHEL that this gets enabled?

**Comment by PHPScaresMe** [comment]
I just realized it's rhel only, the rest have vanilla repos vs `RHOST='repo.madeit.be'`

**Comment by madeITBelgium** [comment]
Hi, yes it is currently rhel (centos) only. Currently, only the installer is not up-to-date and we do not have a Debian repo. But when you install the original vesta and copy this code it might work.
