### ISSUE TITLE
Let's Encrypt ACMEv1 deprecation

### ISSUE THREAD

**Issue by F4bri92** [madeITBelgium/vesta#74]
### Operating System (OS/VERSION):

Centos 7

### VestaCP Version:

0.0.17

### Installed Software (what you got with the installer):

php-fpm (7.2), nginx, MariaDB

### Other Notes:
Received this email from Let's Encrypt:

> Hi,
> 
> According to our records, the software client you're using to get Let's
> Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate
> in the past two weeks using the ACMEv1 protocol. Here are the details of one
> recent ACMEv1 request from each of your account(s):
> 
> Client IP address:  <redacted>
> 
> User agent:  curl/7.29.0
> 
> Hostname(s):  <redacted>
> 
> Request time:  2020-02-03 00:20:05 UTC
> 
> Beginning June 1, 2020, we will stop allowing new domains to validate using
> the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
> then, or certificate issuance will fail. For most people, simply upgrading to
> the latest version of your existing client will suffice. You can view the
> client list at: https://letsencrypt.org/docs/client-options/

**Comment by madeITBelgium** [comment]
Thank you @F4bri92 for reporting this. We got the same message and working on a fix.

**Comment by F4bri92** [comment]
Found this: https://forum.vestacp.com/viewtopic.php?t=19514

Seems that replacing acme-v01 with acme-v02 in letsencrypt scripts solves the problem.
In this fork there's a mix of v1 (v-add-letsencrypt-vesta, v-add-letsencrypt-mail-domain) and v2 (v-add-letsencrypt-user, v-add-letsencrypt-domain) so maybe that's why we received the warning last february.
