### ISSUE TITLE
Exim 4.94 config bug

### ISSUE THREAD

**Issue by madeITBelgium** [madeITBelgium/vesta#76]
sender verify defer for <>: failed to expand "${extract{1}{:}{${lookup{$local_part@$domain}lsearch{/etc/exim/domains/$domain/aliases}}}}": NULL

**Comment by madeITBelgium** [comment]
https://forum.vestacp.com/viewtopic.php?f=12&t=19994

**Comment by madeITBelgium** [comment]
https://bugs.exim.org/show_bug.cgi?id=2602

**Comment by madeITBelgium** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1848283

**Comment by madeITBelgium** [comment]
wget https://ca1.dynanode.net/exim-4.93-3.el7.x86_64.rpm
rpm -Uvh --oldpackage exim-4.93-3.el7.x86_64.rpm

**Comment by ayyilmaz** [comment]
I applied your config file ans smtp 451 error has solved but I get smtp 550 error now.

https://forum.vestacp.com/viewtopic.php?f=12&t=19994&p=82568#p82568

**Comment by dynanode** [comment]
In the new config the DKIM signing is not working. When sending out emails the DKIM signature is missing.

**Comment by madeITBelgium** [comment]
@dynanode do you have any error in your logs?

**Comment by dynanode** [comment]
I´ve tested on exim 4.93, now upgraded to 4.94 and the error is:

Tainted filename for search: '/etc/exim/domains/mydomain.com/aliases'
2020-07-17 14:16:46 H=myhostname.com [106.189.212.196] sender verify defer for <email@mydomain.com>: failed to expand "${extract{1}{:}{${lookup{$local_part@$domain}lsearch{/etc/exim/domains/$domain/aliases}}}}": NULL

**Comment by dynanode** [comment]
Nothing to see in the logs, looks good, but when sending out email the DKIM is set to none.

Excerpt from email sent to Outlook.com

Authentication-Results: spf=pass (sender IP is 95.217.xxx.xxx)
 smtp.mailfrom=mydomain.com; outlook.de; dkim=none (message not
 signed) header.d=none;outlook.de; dmarc=pass action=none

**Comment by dynanode** [comment]
The problem is something with the dkim configuration path I think, because the config is also not signing on exim 4.93

**Comment by madeITBelgium** [comment]
@dynanode DKIM signature is fixed.

**Comment by dynanode** [comment]
Did you test it? Its still the same issue with the new config.

**Comment by madeITBelgium** [comment]
@dynanode for me it is working. I tested with https://www.mail-tester.com/

**Comment by dynanode** [comment]
Hmm ok thats weird it does not work with either exim 4.93 nor 4.94 with this change. You may see if its working on https://dkimvalidator.com/

**Comment by madeITBelgium** [comment]
@dynanode I got this results with exim 4.94:
```
SpamAssassin Score: 0.928
Message is NOT marked as spam
Points breakdown: 
-0.0 SPF_HELO_PASS          SPF: HELO matches SPF record
 0.0 HTML_MESSAGE           BODY: HTML included in message
 0.7 HTML_IMAGE_ONLY_20     BODY: HTML: images with 1600-2000 bytes of
                            words
 0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily
                            valid
-0.1 DKIM_VALID             Message has at least one valid DKIM or DK signature
-0.1 DKIM_VALID_AU          Message has a valid DKIM or DK signature from
                            author's domain
 0.3 HTML_SHORT_LINK_IMG_3  HTML is very short with a linked image
```

Can you check if dkim is enabled for the domain name? Maybe try v-rebuild-mail-domains, maybe some other config is not set correctly.

**Comment by dynanode** [comment]
I've tested it on a different server, there your config is working and DKIM signature is added properly. Thank you very much for your help I will try to investigate further whats the problem on the specific servers.

**Comment by dynanode** [comment]
One last bug from VestaCP forum reported:

xxx@xxx.com R=autoreplay T=userautoreply defer (13): Permission denied: Tainted '/etc/exim/domains/xxx/autoreply.info.msg' (file for userautoreply transport) not permitted
