### ISSUE TITLE
Vesta SSL (Let's Encrypt) Hostname not working

### ISSUE THREAD

**Issue by paulonichio** [madeITBelgium/vesta#79]
### Operating System (OS/VERSION):

CentOS 7.8

### VestaCP Version:

0.0.22

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

When accessing the VestaCP panel, under "Server", "Configure"> "Vesta SSL".

When checking the "Lets Encrypt Support" option to remove the self-signed certificate by Let's Encrypt, when trying to save, nothing happens. No error messages or anything. Not even the checkbox is checked, the self-signed certificate remains the default.

**Comment by madeITBelgium** [comment]
Hi, thank you for notifying me. Can you try the command: `v-add-letsencrypt-vesta`

**Comment by paulonichio** [comment]
Hi;

Perfect! The v-add-letsencrypt-vesta command solved the problem.

There is some way to update the Vesta files, since there have been some changes in the last few days.

Thanks!

**Comment by madeITBelgium** [comment]
When all changes are tested then I will release a new version the update is automatically pushed to all servers (auto-update system). Or by yum update.
