### ISSUE TITLE
Fail2ban ipv6

### ISSUE THREAD

**Issue by madeITBelgium** [madeITBelgium/vesta#85]
Credits webmaster Rob

Hi!  I recently found a bug and want to report a bug in your fail2ban ipv6 scripts. 
I had to manually adjust 2 of your firewall scripts.  I also had to update fail2ban action.d/vesta.conf as the original vesta.conf does not account for ipv6 / does not block ipv6 failures properly

ip6tables does not recognize   icmp-port-unreachable  had to change it to: icmp6-port-unreachable

diff v-update-firewall-ipv6 v-update-firewall-ipv6.bak
156c156
<         echo " -j REJECT --reject-with icmp6-port-unreachable" >> $tmp
---
>         echo " -j REJECT --reject-with icmp-port-unreachable" >> $tmp

diff v-add-firewall-ipv6-ban v-add-firewall-ipv6-ban.bak
70c70
<     -j REJECT --reject-with icmp6-port-unreachable 2>/dev/null
---
>     -j REJECT --reject-with icmp-port-unreachable 2>/dev/null

vesta.conf

# Fail2Ban configuration file for vesta ipv6

[Definition]

actionstart = if [[ "<family>" = "inet4" ]]; then /usr/local/vesta/bin/v-add-firewall-chain <name>; fi;
     if [[ "<family>" = "inet6" ]]; then /usr/local/vesta/bin/v-add-firewall-ipv6-chain <name>; fi;
actionstop =  if [[ "<family>" = "inet4" ]]; then  /usr/local/vesta/bin/v-delete-firewall-chain <name>; fi;
     if [[ "<family>" = "inet6" ]]; then  /usr/local/vesta/bin/v-delete-firewall-ipv6-chain <name>; fi;
actioncheck = if [[ "<family>" = "inet4" ]]; then iptables -n -L INPUT | grep -q 'fail2ban-<name>[ \t]'; fi;  
     if [[ "<family>" = "inet6" ]]; then ip6tables -n -L INPUT | grep -q 'fail2ban-<name>[ \t]'; fi;
actionban =  if [[ "<family>" = "inet4" ]]; then /usr/local/vesta/bin/v-add-firewall-ban <ip> <name>; fi;
     if [[ "<family>" = "inet6" ]]; then  /usr/local/vesta/bin/v-add-firewall-ipv6-ban <ip> <name>; fi;

actionunban = if [[ "<family>" = "inet4" ]]; then  /usr/local/vesta/bin/v-delete-firewall-ban <ip> <name>; fi;
     if [[ "<family>" = "inet6" ]]; then /usr/local/vesta/bin/v-delete-firewall-ipv6-ban <ip> <name>; fi;

**Comment by LiMoon** [comment]
firewallv6 ACCEPT ICMPV6 TO DROP, but IPv6 address ::/0 error
`Error: invalid ip format :: ::/0`
