### ISSUE TITLE
firewallv6 DROP error & cron job not working

### ISSUE THREAD

**Issue by LiMoon** [madeITBelgium/vesta#87]
### Operating System (OS/VERSION):

CentOS 7.8.2003 (Core)

### VestaCP Version:

0.0.24 :36

### Installed Software (what you got with the installer):

host1 php-fpm, nginx, mysql
host2 apache, nginx

### Steps to Reproduce:

1. cron job sudo /usr/local/vesta/bin/v-backup-users not working.
but, type ssh type sudo /usr/local/vesta/bin/v-backup-users is work.

2. firewallv6 ACCEPT ICMPV6 TO DROP, but IPv6 address ::/0 error
`Error: invalid ip format :: ::/0`
![螢幕擷取畫面 2020-09-15 071630](https://user-images.githubusercontent.com/6398246/93147314-7231be00-f723-11ea-979b-359bc699379d.png)

### other note:

my english bad, use translate google.
--
I tried google to search for the answer and found that as long as the cron service is re-run, it can be executed normally.
`service crond restart`
Perhaps after installing the vesta panel, crond may need to be restarted, otherwise he will never execute cron job

**Comment by madeITBelgium** [comment]
Do you have an error of the cronjob? Or how do you know that it is not working? At my servers, it seems to work.

**Comment by LiMoon** [comment]
1. After the system installation is complete. Type `service crond restart`. cron job can work
2. I can't find the log about ipv6 in system.log

**Comment by madeITBelgium** [comment]
Have you tried the command: `v-add-firewall-ipv6-rule 'DROP' '::/0' '0' 'TCP' 'PING'`?
