### ISSUE TITLE
SFTP Backups are not deleted

### ISSUE THREAD

**Issue by dynanode** [madeITBelgium/vesta#90]
When using Vesta´s SFTP backup method in the default setting 3 backups, backup files for the last 3 days are created and also older files are deleted. However this is not done on the Remote SFTP site, no backups are deleted and the backup server has to store one file per day.

**Comment by madeITBelgium** [comment]
The rotation is optional. You can enable or disable it. By default, it should be enabled (Backup rotation is active). 

Can you check this file: cat /usr/local/vesta/conf/sftp.backup.conf
Does it have the ROTATE parameter?

Example:
```
HOST='***.***.***.***'
USERNAME='***'
PASSWORD='***'
BPATH='backup'
PORT='22'
ROTATE='yes'
TIME='20:30:39'
DATE='2020-06-20'
```

Try to add the ROTATE parameter or change it to 'yes'. If you already have this, then this can be a bug.

**Comment by dynanode** [comment]
Oh there is a rotate parameter? Did not know that. Ok then this makes sense. Added it to my config. Thank you.

**Comment by madeITBelgium** [comment]
Thank you. I will reopen this issue the fix this problem for everyone where the parameter is missing. I'm also working on a website to document this kind of small features.
