### ISSUE TITLE
Change Vesta port

### ISSUE THREAD

**Issue by sohamb03** [madeITBelgium/vesta#95]
Hi, 

How do I go about changing the Vesta port? The `nginx.conf` file at `/etc/nginx` doesn't seem to have such a specification neither does any of the folders in `conf.d`. 

Changing it in `VESTA_ROOT/nginx` is of no use either by starting nginx or `vesta-nginx`, none seem to be reading configuration from the file. 

So is the port `8083` hard-coded somewhere? 

I'm on CentOS 7.

**Comment by madeITBelgium** [comment]
The configuration file is located in `/usr/local/vesta/nginx/nginx.conf` after changing the config file you can restart the nginx service by `service vesta restart`.
Maybe you also need to update the firewall.

**Comment by sohamb03** [comment]
Yeah you were correct. I had done that just that I forgot to open the port, Thanks.
