### ISSUE TITLE
Disk Usage Inconsistency

### ISSUE THREAD

**Issue by sohamb03** [madeITBelgium/vesta#97]
The disk space used by a user shown in the panel and the actual disk space used, is inconsistent. 

This is what is shown in the panel:

![ss1](https://user-images.githubusercontent.com/36881434/104810543-47638d80-581b-11eb-95c5-51e15d5cbc58.png)

However, 

```
[root@sohamb03 ~]# du -s /home/xolentum -h
11G     /home/xolentum
```

**Comment by madeITBelgium** [comment]
Do you know which is wrong? Disk, Mail, Database? I just checked my servers and I found the mail was always 0. That is fixed now.

**Comment by sohamb03** [comment]
It's the user directories which is wrong. I dug a bit deeper into this, and found that the inconsistency is because the size of hidden folders isn't being read. 

```
[xolentum@sohamb03 ~]$ du .xolentum -h
11G     .xolentum/lmdb
11G     .xolentum
```

The size of the user directories, shown in the previous screenshot is this

```
[xolentum@sohamb03 ~]$ du -s xolentum -h
526M    xolentum
```
